name: Unittest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test-on-python38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: InstallPython38
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: InstallCrip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: RunTests
        run: |
          pytest test

  test-on-python39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: InstallPython39
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: InstallCrip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: RunTests
        run: |
          pytest test

  test-on-python310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: InstallPython39
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: InstallCrip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: RunTests
        run: |
          pytest test
